# Generated by Django 4.2.6 on 2023-11-23 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('empleado', 'Empleado'), ('nuevo_usuario', 'Cliente')], default='nuevo_usuario', max_length=20),
        ),
    ]
