# Generated by Django 4.2.6 on 2023-11-23 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_cliente',
            field=models.BooleanField(default=False),
        ),
    ]
