# Generated by Django 4.2.6 on 2023-11-26 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_empleado',
            field=models.BooleanField(default=False),
        ),
    ]
