# Generated by Django 4.2.6 on 2023-12-01 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_pedido_fecha_creacion_servicerequest_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='fecha_creacion',
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
