# Generated by Django 4.2.6 on 2023-12-02 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_remove_servicerequest_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='direccion_envio',
            field=models.CharField(default='', max_length=255),
        ),
    ]
