from django.contrib import admin
from django.urls import path
from tasks import views

urlpatterns = [
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),
    path('signup/', views.signup, name='signup'),
    path('tasks/', views.tasks, name='tasks'),
    path('tasks_completed/', views.tasks_completed, name='tasks_completed'),
    path('logout/', views.signout, name='logout'),
    path('signin/', views.signin, name='signin'),
    path('create_task/', views.create_task, name='create_task'),
    path('tasks/<int:task_id>', views.task_detail, name='task_detail'),
    path('taks/<int:task_id>/complete', views.complete_task, name='complete_task'),
    path('tasks/<int:task_id>/delete', views.delete_task, name='delete_task'),
    path('about/', views.about, name='about'),
    path('product/', views.product, name='product'),
    path('store/', views.store, name='store'),
    path('blog/', views.blog, name='blog'),
    path('contact/', views.contact, name='contact'),
    path('password_reset/', views.CustomPasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', views.CustomPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', views.CustomPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', views.CustomPasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('usuarios/', views.user_list, name='user_list'),
    path('editar_usuario/<int:user_id>/', views.editar_usuario, name='editar_usuario'),
    path('activar_usuario/<int:user_id>/', views.activar_usuario, name='activar_usuario'),
    path('desactivar_usuario/<int:user_id>/', views.desactivar_usuario, name='desactivar_usuario'),
    path('ver_perfil/<int:user_id>/', views.ver_perfil, name='ver_perfil'),
    path('servicio1/', views.servicio1, name='servicio1'),
    path('servicio2/', views.servicio2, name='servicio2'),
    path('servicio3/', views.servicio3, name='servicio3'),
    path('manage_user_permissions/<int:user_id>/', views.manage_user_permissions, name='manage_user_permissions'),
]
