from django.contrib import admin
from django.urls import path
from tasks import views

urlpatterns = [
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),
    path('signup/', views.signup, name='signup'),
    path('tasks/', views.tasks, name='tasks'),
    path('tasks_completed/', views.tasks_completed, name='tasks_completed'),
    path('logout/', views.signout, name='logout'),
    path('signin/', views.signin, name='signin'),
    path('create_task/', views.create_task, name='create_task'),
    path('tasks/<int:task_id>', views.task_detail, name='task_detail'),
    path('taks/<int:task_id>/complete', views.complete_task, name='complete_task'),
    path('tasks/<int:task_id>/delete', views.delete_task, name='delete_task'),
    path('about/', views.about, name='about'),
    path('product/', views.product, name='product'),
    path('store/', views.store, name='store'),
    path('blog/', views.blog, name='blog'),
    path('contact/', views.contact, name='contact'),
    path('password_reset/', views.CustomPasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', views.CustomPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', views.CustomPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', views.CustomPasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('usuarios/', views.user_list, name='user_list'),
    path('editar_usuario/<int:user_id>/', views.editar_usuario, name='editar_usuario'),
    path('activar_usuario/<int:user_id>/', views.activar_usuario, name='activar_usuario'),
    path('desactivar_usuario/<int:user_id>/', views.desactivar_usuario, name='desactivar_usuario'),
    path('ver_perfil/<int:user_id>/', views.ver_perfil, name='ver_perfil'),
    path('servicio1/', views.servicio1, name='servicio1'),
    path('servicio2/', views.servicio2, name='servicio2'),
    path('servicio3/', views.servicio3, name='servicio3'),
    path('manage_user_permissions/<int:user_id>/', views.manage_user_permissions, name='manage_user_permissions'),
    path('cliente-products/', views.cliente_products, name='cliente_products'),
    path('cliente_services/', views.cliente_services, name='cliente_services'),
    path('empleado_home/', views.empleado_home, name='empleado_home'),
    path('products/<int:product_id>/', views.product_detail, name='product_detail'),
    path('shopping-cart/', views.shopping_cart, name='shopping_cart'),
    path('add-to-cart/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('productos/', views.product_list, name='product_list'),
    path('editar-producto/<int:product_id>/', views.edit_product, name='edit_product'),
    path('eliminar-producto/<int:product_id>/', views.delete_product, name='delete_product'),
    path('add_product/', views.add_product, name='add_product'),
    path('remove-one/<int:product_id>/', views.remove_one, name='remove_one'),
    path('remove-all/<int:product_id>/', views.remove_all, name='remove_all'),
    path('add-one/<int:product_id>/', views.add_one, name='add_one'),
    path('services/', views.service_list, name='service_list'),
    path('add-service-to-cart/<int:service_id>/', views.add_service_to_cart, name='add_service_to_cart'),
    path('employee/add-service/', views.add_service, name='add_service'),
    path('employee/service-list/', views.employee_service_list, name='employee_service_list'),
    path('services/<int:service_id>/', views.service_detail, name='service_detail'),
    path('edit-service/<int:service_id>/', views.edit_service, name='edit_service'),
    path('delete-service/<int:service_id>/', views.delete_service, name='delete_service'),
    path('services/add_to_cart/<int:service_id>/', views.add_service_to_cart, name='add_service_to_cart'),
    path('adquirir-servicio/<int:servicio_id>/', views.adquirir_servicio, name='adquirir_servicio'),
    path('service-request/<int:service_id>/', views.service_request, name='service_request'),
    path('submit-service-request/<int:service_id>/', views.submit_service_request, name='submit_service_request'),
    path('request-service/<int:service_id>/', views.ServiceRequestView.as_view(), name='request_service'),
    path('pedidos/', views.pedido_list, name='pedido_list'),
    path('buy-products/', views.buy_products, name='buy_products'),
]
